### PR TITLE
Return success/failure by value instead of throw

### PR DESCRIPTION
**Pull request by fixplz**
Replace PEGjs with Waka.

@domenic I was able to write a nicer API for Waka which avoids using exceptions when used for validation, and is mostly a drop-in replacement.

This changes the API for this module to return `{ success: Boolean, error: String }` from the validation functions.

The precompiled parser is now 9KB instead of 29KB in size.

It's possible to eliminate the precompilation step with this because Waka can be used with Browserify.

### CODE REVIEW

**Comment by domenic** [comment]
Thanks! Merging this in since it's ~5x faster according to my tests, on valid inputs at least.

Unfortunately the error messages are much less informative (e.g. it doesn't tell you what it was expecting). And the semicolons are silly. But overall, an improvement.

**Comment by domenic** [comment]
Unfortunately this had to be reverted as it broke several test cases in jsdom. I've added those test cases to this package directly, if you want to try again.

**Comment by fixplz** [comment]
Problem was in a condition I wrote that assumed that reaching EOF was equivalent to success, meaning the empty input always succeeds. (Good to know any small mistake I make in an update can wreck JSDom.)

I don't find PEGjs errors helpful in practice, more so because my interest is in parsing relatively complex languages. Even here you will have better UX by manually writing a descriptive error message instead of emitting the 200+ char listing of valid char ranges you get.

Invalid inputs must be slower because it invokes `new Error()`. It could not do that, but I don't see the benefit.

Measuring performance here is measuring the overhead of invoking the parser (I prefer to measure throughput, in MB/s...), you could improve perf by not using the wrapper API, which will skip a few function calls and an unnecessary try-catch.

**Comment by domenic** [comment]
> Measuring performance here is measuring the overhead of invoking the parser (I prefer to measure throughput, in MB/s...)

Overhead is most important, since this will only be called when people manipulate the DOM, which is rarer than reading it.

**Pull request merged**
